fix: clean code for table merge in Q1
Your solution file either prints output to the console (e.g. through the
print() function, or it fails to run (e.g. throws an error). You must
make sure that the py or ipynb file which you submit does not have
errors. The output we received from the ipthon interpretor was:

  File "/home/marker/grader/assignment3_student_solution.py", line 211

    '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
    '2014', '2015']

    ^

IndentationError: unexpected indent